spring.application.name=exam-jee

spring.datasourcce.url=jdbc:h2:mem:creditdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.passwords=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.dpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console